server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fitmedia-user-db
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    non-secure-port: 8081
    prefer-ip-address: false
    instance-id: localhost:${spring.application.name}:${server.port}
